# Generated by Django 4.1.7 on 2023-04-02 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_alter_todo_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed", "-id"]},
        ),
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
