# Generated by Django 4.1.7 on 2023-04-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0005_alter_todo_options_alter_todo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
